package handlers

import (
	"fmt"
	"net/http"
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/lemnispace/shop-api/internal/models"
	"github.com/lemnispace/shop-api/internal/services"
	"github.com/lemnispace/shop-api/internal/utils"
)

// ProductService is a reference to the product service
var productService services.ProductService

// SetProductService sets the product service for the handlers
func SetProductService(service services.ProductService) {
	productService = service
}

// ListAllProducts handles GET /v1/products
func ListAllProducts(c *gin.Context) {
	// Parse query parameters using Gin
	limit, _ := strconv.Atoi(c.DefaultQuery("limit", "20"))
	cursor := c.Query("cursor")
	status := c.Query("status")
	collection := c.Query("collection")
	sortKey := c.DefaultQuery("sortKey", "created_at")
	sortOrder := c.DefaultQuery("sortOrder", "desc")

	// Build filters
	filters := make(map[string]interface{})
	if status != "" {
		filters["status"] = status
	}
	if collection != "" {
		filters["collection"] = collection
	}

	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	// Get products from service
	result, err := productService.ListProducts(c.Request.Context(), limit, cursor, filters, sortKey, sortOrder)
	if err != nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to fetch products")
		return
	}

	// Construct response directly following the API design spec
	response := gin.H{
		"products": result.Products, // Assuming result.Products has the correct model structure
		"pagination": gin.H{
			"nextCursor": result.NextCursor,
			"hasMore":    result.NextCursor != "", // Basic check if next cursor exists
		},
	}

	utils.JSONResponse(c, http.StatusOK, response)
}

// CreateProduct handles POST /v1/products
func CreateProduct(c *gin.Context) {
	var input models.ProductInput
	if err := c.ShouldBindJSON(&input); err != nil {
		utils.ErrorResponse(c, http.StatusBadRequest, "Invalid request body: "+err.Error())
		return
	}

	// Validate input
	if input.Title == "" {
		utils.ValidationError(c, "title", "Title is required")
		return
	}

	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	// Create a new product model (assuming service handles ID generation)
	product := models.Product{
		// ID is usually generated by the service/database layer
		Title:           input.Title,
		Description:     input.Description,
		Price:           input.Price,
		SKU:             input.SKU,
		Status:          input.Status,
		Inventory:       input.Inventory,
		Tags:            input.Tags,
		CustomFields:    input.CustomFields,
		Dimensions:      input.Dimensions,
		FulfillmentData: input.FulfillmentData,
		CreatedAt:       time.Now(), // Service might handle this
		UpdatedAt:       time.Now(), // Service might handle this
	}

	// Convert ImageInputs to Images
	if len(input.Images) > 0 {
		product.Images = make([]models.Image, 0, len(input.Images))
		for _, imgInput := range input.Images {
			product.Images = append(product.Images, models.Image{
				ID:        fmt.Sprintf("img_%d", time.Now().UnixNano()),
				URL:       imgInput.URL,
				AltText:   imgInput.AltText,
				IsDefault: imgInput.IsDefault,
				Variants:  imgInput.Variants,
				Position:  imgInput.Position,
				CreatedAt: time.Now(),
				UpdatedAt: time.Now(),
			})
		}
	}

	// Call service to create the product
	err := productService.CreateProduct(c.Request.Context(), &product)
	if err != nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to create product: "+err.Error())
		return
	}

	// Process variants if provided in the input
	if len(input.Variants) > 0 {
		createdVariants := make([]models.ProductVariant, 0, len(input.Variants))
		for _, variantInput := range input.Variants {
			if variantInput.Title == "" {
				utils.ErrorResponse(c, http.StatusBadRequest, fmt.Sprintf("Variant title is required for SKU %s", variantInput.SKU))
				return
			}
			variant := models.ProductVariant{
				// ID generated by service?
				ProductID:       product.ID,
				Title:           variantInput.Title,
				SKU:             variantInput.SKU,
				Price:           variantInput.Price,
				Inventory:       variantInput.Inventory,
				Options:         variantInput.Options,
				Dimensions:      variantInput.Dimensions,
				FulfillmentData: variantInput.FulfillmentData,
			}
			err := productService.AddProductVariant(c.Request.Context(), product.ID, &variant)
			if err != nil {
				utils.ErrorResponse(c, http.StatusInternalServerError, fmt.Sprintf("Failed to add variant %s: %v", variant.SKU, err))
				return
			}
			createdVariants = append(createdVariants, variant)
		}
		product.Variants = createdVariants
	}

	utils.JSONResponse(c, http.StatusCreated, product)
}

// GetProduct handles GET /v1/products/:productId
func GetProduct(c *gin.Context) {
	productId := c.Param("productId")
	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	product, err := productService.GetProduct(c.Request.Context(), productId)
	if err != nil {
		if err == services.ErrProductNotFound {
			utils.ErrorResponse(c, http.StatusNotFound, "Product not found")
		} else {
			utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to fetch product: "+err.Error())
		}
		return
	}

	utils.JSONResponse(c, http.StatusOK, product)
}

// UpdateProduct handles PUT /v1/products/:productId
func UpdateProduct(c *gin.Context) {
	productId := c.Param("productId")
	var input models.ProductInput
	if err := c.ShouldBindJSON(&input); err != nil {
		utils.ErrorResponse(c, http.StatusBadRequest, "Invalid request body: "+err.Error())
		return
	}

	if input.Title == "" {
		utils.ValidationError(c, "title", "Title is required")
		return
	}

	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	productToUpdate := models.Product{
		ID:              productId,
		Title:           input.Title,
		Description:     input.Description,
		Price:           input.Price,
		SKU:             input.SKU,
		Status:          input.Status,
		Inventory:       input.Inventory,
		Tags:            input.Tags,
		CustomFields:    input.CustomFields,
		Dimensions:      input.Dimensions,
		FulfillmentData: input.FulfillmentData,
		UpdatedAt:       time.Now(),
	}

	// Convert ImageInputs to Images
	if len(input.Images) > 0 {
		productToUpdate.Images = make([]models.Image, 0, len(input.Images))
		for _, imgInput := range input.Images {
			productToUpdate.Images = append(productToUpdate.Images, models.Image{
				ID:        fmt.Sprintf("img_%d", time.Now().UnixNano()),
				URL:       imgInput.URL,
				AltText:   imgInput.AltText,
				IsDefault: imgInput.IsDefault,
				Variants:  imgInput.Variants,
				Position:  imgInput.Position,
				CreatedAt: time.Now(),
				UpdatedAt: time.Now(),
			})
		}
	}

	err := productService.UpdateProduct(c.Request.Context(), &productToUpdate)
	if err != nil {
		if err == services.ErrProductNotFound {
			utils.ErrorResponse(c, http.StatusNotFound, "Product not found")
		} else {
			utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to update product: "+err.Error())
		}
		return
	}

	updatedProduct, err := productService.GetProduct(c.Request.Context(), productId)
	if err != nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to fetch updated product: "+err.Error())
		return
	}

	utils.JSONResponse(c, http.StatusOK, updatedProduct)
}

// DeleteProduct handles DELETE /v1/products/:productId
func DeleteProduct(c *gin.Context) {
	productId := c.Param("productId")
	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	err := productService.DeleteProduct(c.Request.Context(), productId)
	if err != nil {
		if err == services.ErrProductNotFound {
			utils.ErrorResponse(c, http.StatusNotFound, "Product not found")
		} else {
			utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to delete product: "+err.Error())
		}
		return
	}

	utils.NoContent(c)
}

// ProductCount handles GET /v1/products/count
func ProductCount(c *gin.Context) {
	status := c.Query("status")
	collection := c.Query("collection")
	filters := make(map[string]interface{})
	if status != "" {
		filters["status"] = status
	}
	if collection != "" {
		filters["collection"] = collection
	}

	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	count, err := productService.CountProducts(c.Request.Context(), filters)
	if err != nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to count products")
		return
	}

	utils.JSONResponse(c, http.StatusOK, gin.H{"count": count})
}

// ListAllVariants handles GET /v1/products/variants
func ListAllVariants(c *gin.Context) {
	limit, _ := strconv.Atoi(c.DefaultQuery("limit", "20"))
	cursor := c.Query("cursor")
	sortKey := c.DefaultQuery("sortKey", "created_at")
	sortOrder := c.DefaultQuery("sortOrder", "desc")

	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	variants, nextCursor, err := productService.ListAllVariants(c.Request.Context(), limit, cursor, nil, sortKey, sortOrder)
	if err != nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to fetch variants: "+err.Error())
		return
	}

	utils.JSONResponse(c, http.StatusOK, gin.H{
		"variants": variants,
		"pagination": gin.H{
			"nextCursor": nextCursor,
			"hasMore":    nextCursor != "",
		},
	})
}

// ListProductVariants handles GET /v1/products/:productId/variants
func ListProductVariants(c *gin.Context) {
	productId := c.Param("productId")
	limit, _ := strconv.Atoi(c.DefaultQuery("limit", "20")) // Added pagination
	cursor := c.Query("cursor")

	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	variants, nextCursor, err := productService.ListProductVariants(c.Request.Context(), productId, limit, cursor)
	if err != nil {
		if err == services.ErrProductNotFound {
			utils.ErrorResponse(c, http.StatusNotFound, "Product not found")
		} else {
			utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to fetch product variants: "+err.Error())
		}
		return
	}

	utils.JSONResponse(c, http.StatusOK, gin.H{
		"variants": variants,
		"pagination": gin.H{ // Added pagination response
			"nextCursor": nextCursor,
			"hasMore":    nextCursor != "",
		},
	})
}

// CreateProductVariant handles POST /v1/products/:productId/variants
func CreateProductVariant(c *gin.Context) {
	productId := c.Param("productId")
	var input models.ProductVariantInput
	if err := c.ShouldBindJSON(&input); err != nil {
		utils.ErrorResponse(c, http.StatusBadRequest, "Invalid request body: "+err.Error())
		return
	}

	if input.Title == "" {
		utils.ValidationError(c, "title", "Variant title is required")
		return
	}

	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	variant := models.ProductVariant{
		ProductID:       productId,
		Title:           input.Title,
		SKU:             input.SKU,
		Price:           input.Price,
		Inventory:       input.Inventory,
		Options:         input.Options,
		Dimensions:      input.Dimensions,
		FulfillmentData: input.FulfillmentData,
	}

	err := productService.AddProductVariant(c.Request.Context(), productId, &variant)
	if err != nil {
		if err == services.ErrProductNotFound {
			utils.ErrorResponse(c, http.StatusNotFound, "Product not found")
		} else {
			utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to create variant: "+err.Error())
		}
		return
	}

	utils.JSONResponse(c, http.StatusCreated, variant)
}

// UpdateProductVariant handles PUT /v1/products/:productId/variants/:variantId
func UpdateProductVariant(c *gin.Context) {
	productId := c.Param("productId")
	variantId := c.Param("variantId")
	var input models.ProductVariantInput
	if err := c.ShouldBindJSON(&input); err != nil {
		utils.ErrorResponse(c, http.StatusBadRequest, "Invalid request body: "+err.Error())
		return
	}

	if input.Title == "" {
		utils.ValidationError(c, "title", "Variant title is required")
		return
	}

	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	variant := models.ProductVariant{
		ID:              variantId,
		ProductID:       productId,
		Title:           input.Title,
		SKU:             input.SKU,
		Price:           input.Price,
		Inventory:       input.Inventory,
		Options:         input.Options,
		Dimensions:      input.Dimensions,
		FulfillmentData: input.FulfillmentData,
	}

	err := productService.UpdateProductVariant(c.Request.Context(), productId, &variant)
	if err != nil {
		if err == services.ErrProductNotFound || err == services.ErrVariantNotFound {
			utils.ErrorResponse(c, http.StatusNotFound, "Product or variant not found")
		} else {
			utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to update variant: "+err.Error())
		}
		return
	}

	utils.JSONResponse(c, http.StatusOK, variant)
}

// DeleteProductVariant handles DELETE /v1/products/:productId/variants/:variantId
func DeleteProductVariant(c *gin.Context) {
	productId := c.Param("productId")
	variantId := c.Param("variantId")
	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	err := productService.DeleteProductVariant(c.Request.Context(), productId, variantId)
	if err != nil {
		if err == services.ErrProductNotFound || err == services.ErrVariantNotFound {
			utils.ErrorResponse(c, http.StatusNotFound, "Product or variant not found")
		} else {
			utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to delete variant: "+err.Error())
		}
		return
	}

	utils.NoContent(c)
}

// UploadProductImage handles POST /v1/products/:productId/images
// TODO: Implement product image upload functionality
func UploadProductImage(c *gin.Context) {
	utils.ErrorResponse(c, http.StatusNotImplemented, "Image upload not yet implemented")
}

// AssociateImageWithVariant handles POST /v1/products/:productId/variants/:variantId/images
func AssociateImageWithVariant(c *gin.Context) {
	productId := c.Param("productId")
	variantId := c.Param("variantId")
	var input struct {
		ImageID string `json:"imageId" binding:"required"`
	}
	if err := c.ShouldBindJSON(&input); err != nil {
		utils.ErrorResponse(c, http.StatusBadRequest, "Invalid request body: "+err.Error())
		return
	}

	if productService == nil {
		utils.ErrorResponse(c, http.StatusInternalServerError, "Product service not initialized")
		return
	}

	err := productService.AssociateImageWithVariant(c.Request.Context(), productId, variantId, input.ImageID)
	if err != nil {
		if err == services.ErrProductNotFound || err == services.ErrVariantNotFound || err == services.ErrImageNotFound {
			utils.ErrorResponse(c, http.StatusNotFound, "Product, variant, or image not found")
		} else {
			utils.ErrorResponse(c, http.StatusInternalServerError, "Failed to associate image: "+err.Error())
		}
		return
	}

	utils.JSONResponse(c, http.StatusOK, gin.H{
		"success":   true,
		"variantId": variantId,
		"imageId":   input.ImageID,
	})
}
